### ISSUE TITLE
Invoices outstanding or not yet received

### ISSUE THREAD

**Issue by curtisdelicata** [familytree365/backend#150]
Please email cgdsoftware@outlook.com or cgdwebsites@gmail.com with invoice and reference to work done and you will be paid when the funds arrive for any outstanding invoices.

We are posting this as we believe there may be a couple of outstanding invoices not yet received and paid.

**Comment by devdreamsolution** [comment]
He is a scammer.
I recommend everybody wouldn't work with him.

**Comment by danabrey** [comment]
You believe? Shouldn't you know?
