### ISSUE TITLE
Data scraping of public databases

### ISSUE THREAD

**Issue by curtisdelicata** [familytree365/backend#57]

**Comment by curtisdelicata** [comment]
This also:

https://www.openarch.nl/

**Comment by curtisdelicata** [comment]
https://www.data.gouv.fr/fr/datasets/fichier-des-personnes-decedees/?fbclid=IwAR1c2zG8hN8ZPcWk_3jACPwEiDD-j8WTvwJwfqHZlEEWkN1dJ99q2GJI32U

**Comment by jacira0devdev** [comment]
Don't apply to this scam job.
He will let you work for free and remove you from the issues after you push the code

**Comment by jacira0devdev** [comment]
curtisdelicata is perfect scammer!!!
He doesn't have money and will hire you without any interviews.
Avoid this scammer!!!

**Comment by curtisdelicata** [comment]
Will be re opened at a later date.
