### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by curtisdelicata** [familytree365/backend#9]
Calendar for showing events such as births, deaths and marriages.

**Comment by gilberto31** [comment]
Curtis Delicata is scamer. He doesn't pay any profits. Don't work with him.

**Comment by marcuslie** [comment]
Hi, everyone.
Don't work with this scammer.
Let me explain how he will scam you.
First, he will hire you on Upwork(sometimes PPH, and so on).
Second, he will let you work on a lot of issues and push your updates.
Third, he will let you work without any payment.
Fourth, he will remove you from his GitHub repo, so you will never get paid from this scammer.
He already scammed a lot of developer in this way.
You can check a lot of feedback removed from this scammer.
Don't work with this scammer.
I will report this scammer to GitHub team.
